[local]
localhost ansible_connection=local

[db_primary]
datalayer-1 ansible_host=10.1.2.10

[db_replica]
datalayer-2 ansible_host=10.1.2.20

[app_nodes]
applayer-1 ansible_host=100.74.162.40

[all:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=~/.ssh/iot-bigdata-key.pem

[db_primary:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i ~/.ssh/iot-bigdata-key.pem -W %h:%p -q ec2-user@100.74.162.40"'

[db_replica:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i ~/.ssh/iot-bigdata-key.pem -W %h:%p -q ec2-user@100.74.162.40"'
