- name: Configure TimescaleDB RPM Repository
  ansible.builtin.yum_repository:
    name: timescale_timescaledb
    description: TimescaleDB Official Repository
    baseurl: https://packagecloud.io/timescale/timescaledb/el/9/$basearch
    repo_gpgcheck: true
    gpgcheck: false
    enabled: true
    gpgkey: https://packagecloud.io/timescale/timescaledb/gpgkey
    sslverify: true
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt

- name: Install PostgreSQL 16 packages
  ansible.builtin.dnf: 
    name:
      - postgresql16-server
      - postgresql16
    state: present

- name: Install TimescaleDB
  ansible.builtin.dnf:
    name:
      - timescaledb-2-postgresql-16
    state: present

- name: Symlink TimescaleDB loader
  ansible.builtin.file:
    src: /usr/lib64/timescaledb-loader-pg16/timescaledb.so
    dest: /usr/lib64/pgsql/timescaledb.so
    state: link

- name: Symlink TimescaleDB control file
  ansible.builtin.file:
    src: /usr/lib64/timescaledb-loader-pg16/timescaledb.control
    dest: /usr/share/pgsql/extension/timescaledb.control
    state: link
    force: true

- name: Find TimescaleDB shared engine libraries
  ansible.builtin.find:
    paths: /usr/lib64/timescaledb-pg16
    patterns: "timescaledb-*.so"
  register: timescale_libs

- name: Symlink TimescaleDB engine libraries to PostgreSQL libdir
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "/usr/lib64/pgsql/{{ item.path | basename }}"
    state: link
    force: true
  loop: "{{ timescale_libs.files }}"

- name: Find TimescaleDB extension SQL definitions
  ansible.builtin.find:
    paths: /usr/lib64/timescaledb-pg16
    patterns: "timescaledb--*.sql"
  register: timescale_sqls

- name: Symlink TimescaleDB extension SQL to PostgreSQL extension dir
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "/usr/share/pgsql/extension/{{ item.path | basename }}"
    state: link
    force: true
  loop: "{{ timescale_sqls.files }}"
