- name: Install PostgreSQL 16 packages
  ansible.builtin.dnf: 
    name:
      - postgresql16-server
      - postgresql16
    state: present

- name: Database initialization
  ansible.builtin.command: postgresql-setup --initdb
  args:
    creates: /var/lib/pgsql/data/PG_VERSION

- name: Install TimescaleDB
  ansible.builtin.dnf:
    name:
      - timescaledb-2-postgresql-16
    state: present

- name: Symlink TimescaleDB loader
  ansible.builtin.file:
    src: /usr/lib64/timescaledb-loader-pg16/timescaledb.so
    dest: /usr/lib64/pgsql/timescaledb.so
    state: link

- name: Ensure PostgreSQL service is started and enabled
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: true

- name: Configure postgresql.conf for TimescaleDB and Replication
  ansible.builtin.blockinfile:
    path: /var/lib/pgsql/data/postgresql.conf
    block: |
      shared_preload_libraries = 'timescaledb'
      wal_level = replica
      max_wal_senders = 3
      max_replication_slots = 3
      wal_keep_size = 256MB
      listen_addresses = '*'

- name: Update localhost auth method to scram-sha-256 in pg_hba.conf
  ansible.builtin.replace:
    path: /var/lib/pgsql/data/pg_hba.conf
    regexp: '(127\.0\.0\.1/32\s+|::1/128\s+)ident'
    replace: '\1scram-sha-256'

- name: Configure pg_hba.conf for app nodes and replica nodes
  ansible.builtin.blockinfile:
    path: /var/lib/pgsql/data/pg_hba.conf
    block: |
      # App node access
      host    all             {{ db_user }}       10.0.1.0/24       scram-sha-256
      host    all             {{ db_user }}       10.0.2.0/24       scram-sha-256

      # Streaming replication access 
      host    replication     replicator          {{ replica_ip }}/32       scram-sha-256


- name: Create database and user roles
  ansible.builtin.command: >
    sudo -u postgres psql -c "
    CREATE USER {{ db_user }} WITH PASSWORD '{{ db_password }}';
    CREATE DATABASE {{ db_name }} OWNER {{ db_user }};
    GRANT ALL PRIVILEGES ON DATABASE {{ db_name }} TO {{ db_user }};
    GRANT pg_monitor TO {{ db_user }};
    CREATE USER replicator WITH REPLICATION PASSWORD '{{ db_password }}';
    SELECT pg_create_physical_replication_slot('replica_datalayer2_slot');
    "


