# ============================================================
# prometheus.yml
# Prometheus Configuration for IoT Big Data Project
# ============================================================

global:
  scrape_interval:     15s # Waktu scrape interval default
  evaluation_interval: 15s # Waktu evaluasi rules default

# Alertmanager configuration (opsional untuk masa depan)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules (opsional untuk alert rules)
rule_files:
  # - "alert.rules_yml"

scrape_configs:
  # ----------------------------------------------------------
  # 1. Prometheus Server self-monitoring (PULL Model)
  #    Hanya memantau server Prometheus sendiri
  # ----------------------------------------------------------
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # CATATAN ARSITEKTUR:
  # Metrik host Unix (CPU, RAM, Disk) dan mesin database Postgres
  # dari datalayer-1 dan datalayer-2 tidak ditarik (PULL) dari sini, 
  # melainkan dikirimkan secara aktif (PUSH) oleh Grafana Alloy 
  # melalui endpoint remote write receiver di port 9090.
  #
  # Dengan demikian, kita tidak perlu membuka port masuk (inbound)
  # 12345 pada Security Group database AWS Anda. Ini jauh lebih aman.

